### ISSUE TITLE
Mandatory dependency on ring on unix platforms (including Linux)

### ISSUE THREAD

**Issue by joshtriplett** [rustls/rustls-platform-verifier#102]
`rustls-platform-verifier/Cargo.toml` contains:
```toml
[target.'cfg(all(unix, not(target_os = "android"), not(target_os = "macos"), not(target_os = "ios"), not(target_os = "tvos")))'.dependencies]
rustls-native-certs = "0.7"
webpki = { package = "rustls-webpki", version = "0.102", features = ["ring", "alloc", "std"] }
```

As far as I can tell, this force-enables `ring` on any `unix` platform that isn't `android` or an apple platform.

I maintain a crate with an indirect dependency on `rustls-platform-verifier`, and I'd like to be able to offer my users the option of using `ring`, `aws-lc-rs`, or a custom crypto provider.

Would it be possible to remove this mandatory dependency?
